# Generated by Django 4.0.4 on 2022-05-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=24)),
                ('yoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gramm.yoba')),
            ],
        ),
    ]
