# Generated by Django 4.0.4 on 2022-05-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0002_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='yoba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='gramm.yoba'),
        ),
    ]
