# Generated by Django 4.0.4 on 2022-05-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0008_yoba_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='yobas',
        ),
        migrations.AddField(
            model_name='yoba',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='yobas', to='gramm.tags'),
        ),
    ]
